<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_alta_producto.phtml' ?>


<!-- listado de productos (ABM) -->
<h5>Productos:</h5>
<ul class="list-group">
    <?php foreach ($products as $product) : ?>
        <li class="list-group-item item-task ">
            <div>
                <b><?= $product->tipo ?></b> | <?= substr($product->nombre, 0, 25) ?> | Precio: <?= $product->precio ?>
            </div>

        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando todos los productos</small></p>

<!-- modificacion productos -->
<ul class="list-group">
    <h5>Modificar productos:</h5>
    <?php foreach ($products as $product) : ?>
        <li class="list-group-item item-task <?php if ($product->eliminada) : ?> finalizada <?php endif ?>">
            <div>
                <b><?= $product->tipo ?></b> | <?= substr($product->nombre, 0, 25) ?> | Precio: <?= $product->precio ?>
            </div>
            <div class="actions">

                <!-- precarga de datos a modificar -->
                <form action="products/update/<?= $product->id ?>" method="POST" class="my-4">
                    <div class="row">
                        <div class="col-5">
                            <div class="form-group">
                                <label>Nombre</label>
                                <input required name="newName" type="text" value="<?php echo $product->nombre; ?>" class="form-control">
                            </div>
                        </div>

                        <div class="col-3">
                            <div class="form-group">
                                <label>Categoria</label>
                                <select required name="newCategory" class="form-control">
                                    <?php
                                    $uniqueCategories = []; // Para almacenar categorías únicas

                                    foreach ($products as $product) {
                                        $category = $product->tipo;

                                        // Agregar la categoría al array solo si no existe ya
                                        if (!in_array($category, $uniqueCategories)) {
                                            $uniqueCategories[] = $category;
                                            echo '<option value="' . $category . '">' . $category . '</option>';
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="form-group">
                            <label>Precio</label>
                            <input required name="newPrice" type="text" value="<?php echo $product->precio; ?>" class="form-control">
                        </div>
                    </div>

                    <?php if (!$product->eliminada) : ?>
                        <button type="submit" class='btn btn-success ml-auto'>Modificar</button>
                    <?php endif ?>
                    <!-- <button type="submit" class="btn btn-primary mt-2">Guardar</button> -->
                </form>
                <a href="delete/<?= $product->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> productos</small></p>



<?php require 'templates/footer.phtml' ?>