<?php require 'templates/header.phtml' ?>
<?php require 'templates/form_alta_categoria.phtml' ?>

<!-- listado de categorias (ABM) -->
<h5>Categorias:</h5>
<ul class="list-group">
    <?php
    $shownCategories = []; 
    foreach ($categories as $category):
        if (!in_array($category->tipo, $shownCategories)):
            // Si la categoría no se ha mostrado aún, la mostramos y la registramos.
            $shownCategories[] = $category->tipo;
            ?>
            <li class="list-group-item item-task ">
                <div>
                    <b><?= $category->tipo ?></b>
                </div>
            </li>
        <?php endif;
    endforeach;
    ?>
</ul>


<p class="mt-3"><small>Mostrando categorias</small></p>

<!-- modificacion categorias -->
<ul class="list-group">
     <h5>Modificar categoria:</h5>
    <?php
    $shownCategories = []; 
    foreach ($categories as $category):
        if (!in_array($category->tipo, $shownCategories)):
            // Si la categoría no se ha mostrado aún, la mostramos y la registramos.
            $shownCategories[] = $category->tipo;
            ?>
            <li class="list-group-item item-task ">
            <div>
                <b><?= $category->tipo ?></b>
            </div>
            <div class="actions">

                <!-- precarga de datos a modificar -->
                <form action="categories/update/<?= $category->id ?>" method="POST" class="my-4">
                    <div class="row">
                        <div class="col-5">
                            <div class="form-group">
                                <label>Nombre categoria</label>
                                <input required name="newNameCategory" type="text" value="<?php echo $category->tipo; ?>" class="form-control">
                            </div>
                        </div>
                    </div>

                    <?php if ($category) : ?>
                        <button type="submit" class='btn btn-success ml-auto'>Modificar</button>
                    <?php endif ?>
                </form>
                <a href="delete/<?= $category->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </div>
            </li>
        <?php endif;
    endforeach;
    ?>
</ul>




<?php require 'templates/footer.phtml' ?>