
<section class="descripcion">
        <div class="vinoteca">
            <h5>¡Brindemos!</h5>
            <p>En el corazón de nuestra tienda de bebidas online, te espera un equipo de expertos ansiosos por brindarte asistencia.
               Aquí, no solo encontrarás un catálogo de bebidas, sino un amigo que conoce tus gustos, recuerda tu selección de la semana pasada y hasta con quién lo compartiste. 
            </p>
        </div>
</section>






