<!-- formulario de alta y modificacion de producto -->
<form action="add" method="POST" class="my-4">
    <div class="row">
        <div class="col-5">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="name" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Categoria</label>
                <select required name="category" class="form-control">
                    <?php if ($products) {
                        foreach ($products as $product) {
                            echo '<option value="' . $product->tipo. '">' . $product->tipo . '</option>';
                        }
                    } ?>
                </select>

            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="form-group">
            <label>Precio</label>
            <input required name="price" type="text" class="form-control">
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>