<!-- formulario de alta y modificacion de producto -->
<form action="products/add" method="POST" class="my-4">
    <h2>Dashboard Productos</h2>
    <div class="row">
        <h5>Agregar nuevo producto</h5>
        <div class="col-5">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="name" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Categoria</label>
                <select required name="category" class="form-control">
                    <?php
                    $uniqueCategories = []; // Para almacenar categorías únicas

                    foreach ($products as $product) {
                        $category = $product->tipo;

                        // Agregar la categoría al array solo si no existe ya
                        if (!in_array($category, $uniqueCategories)) {
                            $uniqueCategories[] = $category;
                            echo '<option value="' . $category . '">' . $category . '</option>';
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="form-group">
            <label>Precio</label>
            <input required name="price" type="text" class="form-control">
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>