<!-- //agregar categoria -->
<form action="categories/add" method="POST" class="my-4">
    <h2>Dashboard Categorias</h2>
    <div class="row">
        <h5>Agregar nueva categoria</h5>
        <div class="col-5">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nameCategory" type="text" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-5">Guardar</button>
</form>