
<section class="descripcion">
        <div class="vinoteca">
            <h2>Somos BodegaOnline</h2>
            <p>Somos amantes de las bebidas finas y deseamos que tu experiencia sea más que una simple compra en línea.
               Queremos enriquecer tus conocimientos sobre maridajes, proporcionándote consejos detallados según la variedad de la bebida que elijas.
               También te ofrecemos información valiosa sobre las bodegas y los productores que dan vida a estos elixires. 
            </p>
        </div>
</section>



<section class="descripcion">
        <div class="cepas">
            <h3>¡Bienvenido!</h3>
            <p>Nuestro compromiso es brindarte un catálogo cuidadosamente seleccionado, presentándote no solo bebidas, sino todo un mundo de características y sabores que las hacen únicas.
               En cada botella que ofrecemos, encontrarás historias, tradiciones y el arte de la vinificación.
               ¡Bienvenido a nuestra vinoteca en línea! 🍷🍾
            </p>
        </div>
</section>


