<?php require 'templates/header.phtml' ?>

<section class="descripcion">
        <div class="vinoteca">
            <h2>Nuestra Vinoteca y selección de vinos</h2>
            <p>Detrás de una vinoteca hay un especialista que está deseoso por ayudarte, que se convierte en un amigo, 
                que sabe que te llevaste la semana anterior, o con quien lo compartiste, o con que lo vas a maridar 🍽 
                En este sentido deseamos ofrecer a partir de nuestra pagina consejos de maridaje según la cepa que 
                compone al vino, e información sobre distintas bodegas.
                Es por ello que ofrecemos un listado de nuestros vinos seleccionados y sus caracteristicas. 
            </p>
        </div>
        <figure>
            <img class="img" src="images/vinoteca.jpg" alt="vinoteca">
        </figure>
</section>

<section class="descripcion">
        <div class="bodegas">
            <h2>Nuestra Seleccion de bodegas</h2>
            <p>Una bodega es una instalación que, junto con los equipos de almacenaje, de manipulación, medios humanos 
                y de gestión, nos permite regular las diferencias entre los flujos de entrada de mercadería (la que se
                recibe de proveedores, centros de fabricación, etc.) y los de salida (aquella mercadería que se envía a 
                la producción, la venta, etc.)
                Nos complace compartirles nuestra Selección Exclusiva de bodegas, una breve desccripción de ella, 
                y los vinos asociados a estas. 
            </p>
        </div>
        <figure>
            <img class="img" src="images/bodega.jpg" alt="bodega">
        </figure>
</section>

<section class="descripcion">
        <div class="cepas">
            <h2>Nuestra Seleccion de cepas</h2>
            <p>Las cepas son las diferentes variedades de vides que producen diversos tipos de uvas con características 
               diferenciadoras. Estas pueden localizarse en ámbitos geográficos concretos, aunque gracias a las técnicas 
               de viticultura se van extendiendo, y se reproducen mediante esquejes, injertos y acodos.
               Es por ello que compartimos con ustedes en este sitio nuestra seleccion de cepas, los vinos asociadas a ellas,
               y una breve descripción de las mismas! Esperamos que disfruten de esta información!
            </p>
        </div>
        <figure>
            <img class="img" src="images/cepas.jpg" alt="cepa">
        </figure>
</section>


<?php require 'templates/footer.phtml' ?>