<?php require './templates/header.phtml' ?>
<?php require './templates/home.phtml' ?>
<!-- listado de productos (ABM) -->
<h5>Productos:</h5>
<ul class="list-group">
    <?php foreach ($products as $product) : ?>
        <li class="list-group-item item-task ">
            <div>
                <b><?= $product->tipo ?></b> | <?= substr($product->nombre, 0, 25) ?> | Precio: <?= $product->precio ?>
            </div>

        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> productos</small></p>
<?php require './templates/description.phtml' ?>
<?php require './templates/footer.phtml' ?>