<?php require 'templates/header.phtml' ?>

<!-- 
$clave = "admin";  
$clave_encriptada = password_hash ($clave , PASSWORD_BCRYPT );  
echo "La clave $clave encriptada es la siguiente: $clave_encriptada";  
-->


<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="usuario">Usuario</label>
            <input type="text" required class="form-control" id="usuario" name="usuario" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?> 


