<?php require './templates/header.phtml' ?>




<!-- listado de categorias (ABM) -->


<div  class="col-3">
    <form action="home/list/<?= $category->id ?>" method="POST" <div class="form-group">
        <label>Categoria</label>
        <select required name="newCategory" class="form-control">
            <?php
            $uniqueCategories = []; // Para almacenar categorías únicas

            foreach ($categories as $category) {
                $category = $category->tipo;

                // Agregar la categoría al array solo si no existe ya
                if (!in_array($category, $uniqueCategories)) {
                    $uniqueCategories[] = $category;
                    echo '<option value="' . $category . '">' . $category . '</option>';
                }
            }
            ?>
        </select>
        <button type="submit" class="btn btn-primary mt-2">Mostrar Productos</button>
</div>
</form>
</div>



<p class="mt-3"><small>Mostrando <?= $count ?> productos</small></p>


<?php require './templates/footer.phtml' ?>